services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=akademika-db'
      - 'POSTGRES_PASSWORD=akademika-secret'
      - 'POSTGRES_USER=akademika-user'
    ports:
      - "5432:5432"

  etcd:
    image: quay.io/coreos/etcd:v3.5.14
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    ports:
      - "2379:2379"

  minio:
    image: minio/minio:latest
    command: minio server /minio_data --console-address ":9001"
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    ports:
      - "9000:9000"
      - "9001:9001"

  milvus-standalone:
    image: milvusdb/milvus:v2.4.9
    command: ["milvus", "run", "standalone"]
    depends_on:
      - etcd
      - minio
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      - "ETCD_ENDPOINTS=etcd:2379"
      - "MINIO_ADDRESS=minio:9000"