# Configuração do Banco de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:testdb  # URL para um banco em memória chamado 'testdb'
spring.datasource.driverClassName=org.h2.Driver # Driver do H2
spring.datasource.username=sa             # Usuário padrão do H2
spring.datasource.password=               # Senha padrão (vazia)
spring.h2.console.enabled=true            # Habilita o console H2 (opcional, útil para debug)
spring.h2.console.path=/h2-console        # Path para aceder ao console (ex: http://localhost:8080/h2-console)

# Configuração do JPA/Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect # Dialeto SQL para H2
spring.jpa.hibernate.ddl-auto=create-drop # CRIA o schema ao iniciar e APAGA ao terminar. Ótimo para testes!
                                           # Outras opções: 'create', 'update', 'validate', 'none'
spring.jpa.show-sql=true                   # Mostra o SQL gerado no console (útil para debug)
spring.jpa.properties.hibernate.format_sql=true # Formata o SQL mostrado (útil para debug)

# Não se esqueça da chave secreta JWT
api.security.token.secret=SUA_CHAVE_SECRETA_LONGA_E_SEGURA
spring.docker.compose.enabled=false