 spring.datasource.url=jdbc:h2:mem:testdb
 spring.datasource.driverClassName=org.h2.Driver
 spring.datasource.username=sa
 spring.datasource.password=
 spring.h2.console.enabled=true
 spring.h2.console.path=/h2-console
 spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- Adicione as configurações do Postgres ---
#spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
#spring.datasource.username=myuser
#spring.datasource.password=secret
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Mantenha create-drop ou mude para update ---
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Habilite a integração do Docker Compose ---
# Isso ajudará o Spring a esperar o Postgres iniciar
spring.docker.compose.enabled=false

api.security.token.secret=weqwewquyeuwqyeuiqwyeuicjkcxjkhfdsdjkfryqiuwery22ewcaupoiecuhn9vwqevuwioeuqq9i8w7fhq78374gh893p749hj58

spring.ai.openai.api-key=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

spring.ai.vectorstore.milvus.host=localhost
spring.ai.vectorstore.milvus.port=19530
spring.ai.vectorstore.milvus.uri=http://localhost:19530